services:
  lantern:
    container_name: lantern
    image: docker.io/ssfdust/lantern:7.8.6
    build: .
    ports:
      # UI
      - target: 8080
        host_ip: 127.0.0.1
        published: 39332
        protocol: tcp
      # SOCKS proxy
      - target: 1080
        host_ip: 127.0.0.1
        published: 39331
        protocol: tcp
    volumes:
      - data:/home/lantern/.lantern
volumes:
  data:
    name: lantern
