name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/docker-image.yml"
      - "Dockerfile"
      - "settings.yaml"
      - "binaries"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        lfs: true

    - run: >-
        echo "LANTERN_VERSION=$(
          dpkg-deb -I binaries/lantern-installer-64-bit.deb |
          sed -n 's/^ Version: \(.*\)/\1/p'
        )" >> $GITHUB_ENV

    - name: Build Docker Image
      run: >-
        docker build
        --tag docker.io/ssfrust/lantern:latest
        .

    - name: Dump Docker Image
      run: >-
        docker save
        docker.io/ssfrust/lantern:latest
        > lantern.tar

    - name: Upload Docker Image
      uses: actions/upload-artifact@v2
      with:
        name: lantern.tar
