name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      dev:
        description: "Run as development?"
        type: boolean
        required: true
        default: false
  push:
    branches: [ "ci" ]
    paths:
      - ".github/workflows/docker-image.yml"
      - "Dockerfile"
      - "settings.yaml"
      - "binaries"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        lfs: true

    - run: >-
        echo "LANTERN_VERSION=$(
          wget -q https://github.com/getlantern/lantern-binaries/raw/main/lantern-installer-64-bit.deb -O lantern-installer-64-bit.deb
          dpkg-deb -I lantern-installer-64-bit.deb |
          sed -n 's/^ Version: \(.*\)/\1/p'
        )" >> $GITHUB_ENV

    - run: >-
        echo "DATE=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

    - name: Build Docker Image
      run: >-
        docker build
        --tag docker.io/ssfrust/lantern:latest
        .

    - name: Dump Docker Image
      run: >-
        docker save
        docker.io/ssfrust/lantern:latest
        > lantern.tar

    - name: Upload Docker Image
      uses: actions/upload-artifact@v2
      with:
        path: lantern.tar

    - name: Create tag and release
      uses: softprops/action-gh-release@v0.1.14
      if: ${{ github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.dev == 'false') }}
      with:
        name: Lantern image ${{ env.LANTERN_VERSION }} Build ${{ env.DATE }}
        tag_name: ${{ env.DATE }}
        body: lantern ${{ env.LANTERN_VERSION }} Build ${{ env.DATE }}
        files: |
          lantern.tar
